### ISSUE TITLE
Interacting force ranges and exploring the simulation space using the WSAD keys or arrow keys. 

### ISSUE THREAD

**Issue by KhadrasWellun** [tom-mohr/particle-life-app#2]
Hi! I have a request. I noticed that navigating through the simulation space is only done by zooming in and using the mouse wheel. This is extremely annoying when you want to explore the space closely, navigating at a certain zoom level. If you want to make a movie of what's there, it's difficult and annoying to keep pressing the Z key to go back to an overview so you know where to go next. Then, I noticed that there is a matrix of interaction force intensities, but not a matrix of action radii. Each color should interact at different distances with the other colors not just at different intensities. For example, red with blue should interact with a force "x" over a distance "y", and red with green with a force "z" over a distance "w", with x≠y≠z≠w. More interesting would be if each color emitted both an attractive and a repelling force to each other color, not just one kind of force. Thus, red would emit an attractive force of intensity "f1" over a distance "r1" from green, but also a repulsive force "f2" over a distance "r2" also from green. If f1 = f2 and r1 = r2, then the two colours do not interact at all. But if f1 = f2 and r1 < r2, then the two colours do not interact over distance r1, but repel each other over distance r2 - r1. 
What do you think about all this? Could you modify your application to implement them?

**Comment by tom-mohr** [comment]
Hi! Thank you for your request! And sorry for my late reply 😁

You're absolutely right, the app needs better camera controls. In addition to WASD controls I would also love to add the ability to wheel-click on a bunch of particles and then have the camera follow them automatically. This would make it a lot easier to take videos of moving structures. I will need to see if I find time to implement these things soon and will let you know here when I did.

Concerning the radii matrix, I would rather not do that. One of the things that I tried with this app is to boil Particle Life down to its very core: Just the attraction matrix describes a world, everything else is universal across all types of particles. And this still results in very beautiful, complex, life-like behavior. The app should also not be bloated with features -- the GUI is already very packed. In my experience, having more parameters per particle type only produces somewhat more complex structures but doesn't add anything completely new to what we see in Particle Life. It makes it even harder to analyze and explain how these structures arise, because now we have to take more parameters into account.

About the two forces: You're probably inspired by the weak and the strong force in atoms. If we have two forces with different shapes, we can just add them together and think of them as one force with a more complex shape. Currently, the force used in this app looks like this (where `a` is the value in the attraction matrix):
![image](https://user-images.githubusercontent.com/24864629/204139564-e49d441a-e88f-45db-83d3-15a436b5c86d.png)
This is already trying to mimic a bit what happens if we have a repulsive "strong force" (red) and an attractive/repulsive "weak force" (blue). We could of course make the read part variable as well. So you basically propose to have more parameters controlling the shape of this force. But as I said before, I would like to keep things as simple as possible 😉

However, you can also just modify the source code and try out these changes yourself. And let me know if you discover anything crazy!

**Comment by KhadrasWellun** [comment]
Yes, I was thinking of the four fundamental forces in physics: the gravitational force, the electromagnetic force, the strong nuclear force and the weak nuclear force. Why did I think that and not otherwise? Well, the way the application parameters are defined now, at some point, after all the particles have clustered, nothing happens. If there were a force with infinite range that depended on particle mass and not color, it would bring all the particle groups closer together and they would interact again. Then, each group of coupled particles would produce a residual force, as a result of the combination of the coloured forces between the particles of that group, like the electromagnetic force, which could group the groups already formed by the coloured forces into much more complex structures. And if we add to this whole system of forces a probability of those colours interacting with each other, a chain of combinations between particles and groups of particles would propagate throughout the simulation field. If we also introduce reactivity between particles then the picture is complete and interesting and dynamic structures would result. Reactivity is a kind of chemistry, whereby two particles touching have a probability of changing colour after a predetermined matrix of reactions. This whole complex of parameters is what I keep thinking about. What do you make of all this? How do you see it?

**Comment by tom-mohr** [comment]
I think all of that'd be very interesting. That's basically trying to make a very simple copy of the real universe.

About the chemistry: Sounds cool, but that's still a very vague idea. How would this reaction matrix look like? When exactly do two particles react? Are reactions between more than two particles possible (e.g. red+yellow+green=blue)?
And, I think this is not in the scope of this project. Here, I want to really explore the simple idea of Particle Life and make it as cool to use as possible. That doesn't mean that I don't like the idea.

I've also been thinking about adding long-range forces to allow for larger structures. That would be in the scope of the project. But with that I don't mean a different kind of forces, but just having the current force "fade out" (e.g. with 1/r²) instead of hitting zero at `rmax`:
![image](https://user-images.githubusercontent.com/24864629/204165743-08ae795b-b4bb-45fd-b0c3-944729e8cdc2.png)
That would already lead to larger structures. However, the current implementation doesn't allow that: The reason why the app can simulate such a high number of particles accurately in real-time (more than any other implementation I've seen) is that it makes use of the fact that the force is zero after a certain distance (`rmax`). To maintain that level of performance, we'd have to approximate the part of the force after `rmax` somehow, e.g. by only picking some random particles or by using a grid to aggregate the forces of multiple particles into one vector per color.

**Comment by KhadrasWellun** [comment]
The idea of chemistry is already successfully implemented in an app called The Insane Meta Universe.
Check it out here: https://www.youtube.com/watch?v=PbzBuD-Bee0
The app can be found here: https://buddhaman.itch.io/tims-insane-meta-universe
I was referring to the fact that the gravitational force is an additional force in the simulation, different from the colored one, and it is very weak. It doesn't affect the colored forces, it just brings the particles closer, slowly and surely.

**Comment by tom-mohr** [comment]
Oh yeah, I forgot about that! Nice. I see that you commented on that as well and requested a gravitational force 😉

Just implemented camera movement with arrow keys, check out the release: <https://github.com/tom-mohr/particle-life-app/releases/tag/v1.1.0>
I'll close this issue now.
