### ISSUE TITLE
Set Icon in GLFW

### ISSUE THREAD

**Issue by tom-mohr** [tom-mohr/particle-life-app#5]
The application doesn't have an icon when running (only the .exe). Use GLFW to load the existing "favicon.ico" file as application icon.

**Comment by y-ashaswini** [comment]
Greetings!
I was just trying to take up this issue since I really like what you've created, I highly appreciate the level of skill you must possess to create such an application, and I merely wanted to try and contribute to it.

Thing is, I managed to add an icon into it, but the code crashes when it's with an .ico extension. I added a png file instead (just for checking) and it runs.

Is it possible for you to add a png version of the icon into the repo? Or, do you necessarily want it to be .ico?
If you want any more information, please do ask!

**Comment by tom-mohr** [comment]
Greetings! Sorry for replying late. And thanks for the praise :)
Good to hear that you're working on this! Here's a 512x512 PNG:
![image](https://user-images.githubusercontent.com/24864629/235752580-4712f008-77e8-4dff-a9ea-d184a6963bf3.png)

**Comment by y-ashaswini** [comment]
Great! I made the changes.
